### ISSUE TITLE
Release asset naming pattern changed

### ISSUE THREAD

**Issue by harshjv** [yudai/homebrew-gotty#1]
Latest release of GoTTY `v0.0.12` broke the brew installation because release asset naming pattern is changed.

```
==> Installing gotty from yudai/homebrew-gotty
==> Downloading https://github.com/yudai/gotty/releases/download/v0.0.12/darwin_amd64.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "gotty"
Download failed: https://github.com/yudai/gotty/releases/download/v0.0.12/darwin_amd64.tar.gz
```

Actual asset name is **gotty_darwin_amd64.tar.gz** for `v0.0.12`, whereas previous asset had this name: **darwin_386.tar.gz**

**Comment by yudai** [comment]
Closing as it seems it's resolved.
