### ISSUE TITLE
Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by jasonchaffee** [yudai/homebrew-gotty#3]
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/yudai/homebrew-gotty/gotty.rb:8:in `class:Gotty'
Please report this to the yudai/gotty tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/yudai/homebrew-gotty/gotty.rb:8:in `class:Gotty'
Please report this to the yudai/gotty tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/yudai/homebrew-gotty/gotty.rb:8:in `class:Gotty'
Please report this to the yudai/gotty tap!

**Comment by yudai** [comment]
Thank you for the report. It's fixed now.
